### ISSUE TITLE
Multi-Line Values?

### ISSUE THREAD

**Issue by c0nnex** [bwanders/dokuwiki-strata#16]
I have Data-entries which have a Description, which can be more than one line.
Is there any builtin way to handle/declare those?
right now only the first line is shown and i get the error 
```
I don't understand data entry line ' (second line of description)'
```

**Comment by bwanders** [comment]
At the moment, there is no way of declaring multi-line values.

However, if you are using the `wiki` type, e.g., have a `Description [wiki]` field, you can use a trick of the dokuwiki syntax: you can force a newline in the rendered output. This works as follows:
```
Description [wiki]: The first line.\\ The second line.
```
This is [built-in dokuwiki syntax](https://www.dokuwiki.org/wiki:syntax#basic_text_formatting). You can even place double forced new lines to present the appearance of a new paragraph: `...end of paragraph.\\ \\ The next paragraph...`

Does that help?

**Comment by c0nnex** [comment]
Ah yes ... I always tried 
Description [type:.wiki]: .... .\\ next line
but that did not work ... without the type:: it works and is enough for my needs.
Thanks
