### ISSUE TITLE
Incompatibility with plugin:move

### ISSUE THREAD

**Issue by dwdenise** [bwanders/dokuwiki-strata#23]
We use both the move and strata plugins.  We recently moved some pages that were linked in strata blocks using [wiki] hints.  The links in the strata blocks were not updated.

The move plugin's docs at https://www.dokuwiki.org/plugin:move say "this plugin uses the DokuWiki parser which allows it to correctly identify all links and nothing else."

Can you expose links embedded in strata blocks with [wiki] hints via the DokuWiki parser, such that other plugins can find them?

**Comment by bwanders** [comment]
I discovered that this isn't an incompatibility per sé...

As far as I am aware the Strata plugin already uses the correct DokuWiki parser methods to make sure that link metadata is available to other plugins. That is why backlinks also inlcude pages only linked through Strata.

The issue you describe has to do with the fact that plugin:move can only use the parser meta-data to discover which pages need to change. To actually update them, plugin:move explicitly requires other plugins to handle the custom page move events when a page is moved: https://www.dokuwiki.org/plugin:move#support_for_other_plugins.

While I would very much like to implement page move handling, I do not currently have the spare time to put into this. I'll happily accept pull-requests in this direction.

**Comment by Klap-in** [comment]
An example of a similar plugin that could be helpful for who is interested in implementing this:
https://github.com/cosmocode/dokuwiki-plugin-struct/blob/master/action/move.php
