### ISSUE TITLE
Does Strata have an entry UI?

### ISSUE THREAD

**Issue by iainhallam** [bwanders/dokuwiki-strata#25]
I'd like to create a bunch of information for our users, and then have them update it. Can this be done through inputs like date pickers somehow, rather than having to do text entry for every field?

**Comment by bwanders** [comment]
Unfortunately, no.

At least, not out of the box. Something like this has been on our wishlist for a long time, but we have not had time to actually work on it.

**Comment by iainhallam** [comment]
I have no time, unfortunately; but will follow with interest!

**Comment by FosseWay** [comment]
I'm also interested in this idea. I can't take the whole thing on right now, but I'd be happy to help with testing, documentation, or bugfixes.
