### ISSUE TITLE
[wiki] type does not respect root namespace

### ISSUE THREAD

**Issue by Xeenych** [bwanders/dokuwiki-strata#27]
I have a page namespace1:somepage

Variant A
<data>
description[wiki]: [[somepage|]]
</data>

Variant B
<data>
description[wiki]: [[:somepage|]]
</data>

Variant C
<data>
description[wiki]: [[namespace2:somepage|]]
</data>

Variant A and C work as intended but Variant B does not make link to root namespace. It makes link to namespace1:somepage

**Comment by bwanders** [comment]
Good catch!

Fixed with 692980c07f6324cdbc290e60ac9ed43d360e82fe.
