### ISSUE TITLE
Is this addon compatible with file syncing?

### ISSUE THREAD

**Issue by mlinchitstest** [bwanders/dokuwiki-strata#29]
`Question`
If I use dropbox to sync dokuwiki (but not database files obviously) across computers, can I still use this addon? I know most programs that use databases cannot be synced without loss of data, but maybe strata just gets all the data it needs from the text files alone (and then maybe caches them in a database).

Say you take dokuwiki file with some strata records to another computer and edit it in a plain text editor. You then sync the file back to the computer where strata is installed. Does strata know I changed anything?

Thanks

**Comment by bwanders** [comment]
Unfortunately, it does not.

Strata uses Dokuwiki's event system to notice that a page has been saved. External changes are therefore not detected.

It would probably work if you also sync the databse file; but I have no idea how that would turn out in practice.
