### ISSUE TITLE
hard limit results

### ISSUE THREAD

**Issue by dhighet** [bwanders/dokuwiki-strata#39]
As noted in #28 pagination seems to be a complicated solution, but is there a way to just hard cap the amount to display? Say I'm just wanting to display the last 10 items added?

**Comment by bwanders** [comment]
Unfortunately, limiting the number of output results is not possible at the moment.

I agree that this would be a nice to have.

**Comment by dhighet** [comment]
Understandable. I've managed a solution that works for me, for now at least.

I'm currently creating entries via [Bureaucracy](https://www.dokuwiki.org/plugin:bureaucracy), so with that I'm appending dates to the entries. On my main page, I'm filtering only results to show by month using [Date](https://www.dokuwiki.org/plugin:date) to get the current year/month, with the following lines in my `<table>`.

```
?p Created [date]: ?date
?date > {{date> %Y-%m}}
```

I was surprised it worked!

**Comment by FosseWay** [comment]
I found #39 because I wanted to display e.g. the 5 most recent events from an event table on the front page of my wiki.

Thank you @bwanders for the guidance above. I don't know if I will have time in the near future to attempt to implement this, but I hope to do it at some point.
