### ISSUE TITLE
~~INFO:stratatypes~~ crashes wiki

### ISSUE THREAD

**Issue by pop-ch** [bwanders/dokuwiki-strata#47]
using Release rc-2020-06-09 "Hogfather" RC3; using the directive \~~INFO:stratatypes~~ produces an error message:

Fatal error: Uncaught Error: Class 'plugin_strata_type_AbstractBaseType' not found in /volume1/web/dokuwiki/lib/plugins/strata/helper/util.php:50 Stack trace: #0 /volume1/web/dokuwiki/lib/plugins/strata/helper/util.php(62): helper_plugin_strata_util->_load('type', 'AbstractBaseTyp...', 'text') #1 /volume1/web/dokuwiki/lib/plugins/strata/syntax/info.php(51): helper_plugin_strata_util->loadType('AbstractBaseTyp...') #2 /volume1/web/dokuwiki/inc/parser/handler.php(279): syntax_plugin_strata_info->handle('~~INFO:strataty...', 5, 25670, Object(Doku_Handler)) #3 /volume1/web/dokuwiki/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin('~~INFO:strataty...', 5, 25670, 'strata_info') #4 /volume1/web/dokuwiki/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('~~INFO:strataty...', 5, 25670) #5 /volume1/web/dokuwiki/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '~~INFO:strataty...', '_plugin_strata_...', 25670, 25670) #6 /volume1/web/dokuwiki/inc/Parsing/Parser.php(1 in /volume1/web/dokuwiki/lib/plugins/strata/helper/util.php on line 50

This is unfortunate as I am unable to produce a complete list of supported types. The directive for listing the aggregates (\~~INFO:strataaggregates~~) works correctly.

**Comment by bwanders** [comment]
That is indeed unfortunate.

To get some additional context, can you tell me if you have any other plugins active at the same time? And if you changed any of Strata's default configuration, that would be helpful to know as well. Thanks!

**Comment by pop-ch** [comment]
I run the wiki in a wiki farm; however the problem also occurs in a standalone wiki. In the testing wiki I have the following plugins active: 
Plugins active in this instance:	acl, authplain, config, info, sqlite, strata, usermanager
The strata configuration is unchanged. Otherwise, strata works quite well

**Comment by bwanders** [comment]
This bug was due to some other plugin (not one of the ones you mentioned as being active) having a file `types/AbstractBaseType.php` in their plugin structure. I have added a sanity check to autoload function to prevent this case from breaking things.

**Comment by pop-ch** [comment]
Now it works. Thank you very much.
