### ISSUE TITLE
Type "wiki" does not work

### ISSUE THREAD

**Issue by pop-ch** [bwanders/dokuwiki-strata#50]
Using the type "wiki" either in a data block or in a query results in an error message. See the attached wiki page. My wiki is running Release rc-2020-06-09 "Hogfather" RC3

I have found where the list of known data types comes from and I have found "wiki" there. Is it supposed to be working?

[wiki_issue.txt](https://github.com/bwanders/dokuwiki-strata/files/4946550/wiki_issue.txt)

**Comment by bwanders** [comment]
Everything in the `master` branch is supposed to be working. I think this issue (and several others) stem from the fact that the world has changed around the Strata plugin. New ways of including source files to get class definitions, and refactors on the DokuWiki code have made the Strata codebase outdated (which is somewhat expected after 4 years of no updates ^_^)

**Comment by pop-ch** [comment]
I think so, too. 

I will keep on reporting issues if any more will pop up, but will leave it, of course, to your discretion whether you will continue maintaining the plugin. I cetainly hope that you will, though. This seems to be highly valuable for some of my projects.

**Comment by bwanders** [comment]
This issue has to do with the refactor of the DokuWiki codebase in the Hogfather release.

I have fixed it, but in doing so I have also dropped support fro Greebo. Keeping both versions up to date is a time investment I cannot commit to.

**Comment by pop-ch** [comment]
Great! Now this is to me a very useful "extension" to the already useful strata. It works very well. Thank you so much!
