### ISSUE TITLE
Scoped mode

### ISSUE THREAD

**Issue by fkaag71** [bwanders/dokuwiki-strata#55]
Dear Mr Wanders,

I have used your Strata plugin to improve a DokuWiki based tool that I use for risks analysis.

I needed some extra features, and implemented them the best I could:
* a "scoped" mode, where datasets are restricted to a single namespace (I use a same Wiki with different namespaces for each of my clients)
* some kind of enumerated type

I implemented them as well as I could with the attached changes.

The scoped mode relies upon a new "scope" column in the data table, that receives the namespace of the subject page. Depending upon the "scoped" configuration attribute, a filter on this column is added to the SELECT request.

The enumerated type is fully contained in the enum.php file. It displays the full text for a shorthand code or value, taking the replacement from a resource identified by the hint attribute. For example, Criterion [enum::params#criteria]: C  displays as 'Confidentiality' since the Confidentiality: C entry exists in the params#criteria fragment.

At least for the scoped mode, I would be grateful if you could consider to include it into the plugin, rather that maintaining it on my own. I can probably handle the enum in a separate plugin if you think it is not relevant.

[Strata delta.zip](https://github.com/bwanders/dokuwiki-strata/files/7787843/Strata.delta.zip)
[Strata diff.txt](https://github.com/bwanders/dokuwiki-strata/files/7787906/Strata.diff.txt)

Best regards,
François KAAG

**Comment by fkaag71** [comment]
EDIT - After writing this I realized that for the scoped mode I had a much simpler solution, that did not require to alter the data table, thus preserved immediate compatibility. Beside the additional  configuration parameter, the only change is in the _trans_tp function, where the scope is searched as the beginning of the graph name.

The only functional difference is actually an improvement, where a page in a namespace will be granted visibility to data in the namespace children.

[Strata delta2.zip](https://github.com/bwanders/dokuwiki-strata/files/7788153/Strata.delta2.zip)

**Comment by bwanders** [comment]
Due to time constraints I am no longer able to maintain the set of Strata dokuwiki plugins. Which, unfortunately, has lead me to archive the repositories.

I'm sorry that your first experience on github is someone archiving the repository your wanted to contribute to. I hope this does not turn you away form contributing to other open source projects!
