### ISSUE TITLE
Page title [[]] as part of Fragment

### ISSUE THREAD

**Issue by jakreiter** [bwanders/dokuwiki-strata#57]
Is it possible to use current page title [[]] as part of Fragment?

`<data grp #[[]] test>`

Does not resolve [[]].

**Comment by bwanders** [comment]
That's not possible at the moment.

The reason being that the page name is already part of the full identifier of the data block. The fragment is there just to identify the, well, fragment of data on that page.

**Comment by jakreiter** [comment]
Thank you for your prompt reply!
