### ISSUE TITLE
Table's first column

### ISSUE THREAD

**Issue by boozledorf** [bwanders/dokuwiki-strata#7]
I'm trying to create tables of information about our network using this tool, and it's excellent at being able to collect the specific information I need from each device's page, which is excellent.

The only issue I'm having is that when it renders a table  query (say, a device, its MAC address, and its IP address), I have no way of deciding how the device's name gets displayed -- it will always render the device's page name (e.g. "floor_0_cam_ap_switch" or "fiber_switch").

I'd like to be able to provide neat and clean entry for the columns; say, the "entry title" field manually specified in the data block (which doesn't change how the query renders the name, I've discovered), or a field that I can choose in the query itself.  I don't know if I'm overlooking something, but I couldn't find it in the reference guide, and I don't want to spend a day pouring over the source code to see if there's an alternative.

The following table was generated using the code
```
<table ?d "Device" ?i "Internal IP" ?a "MAC Address">
?d is a: switch
?d ~> sca
?d IP [link]: ?i
?d MAC: ?a
</table>
```

![strata](https://cloud.githubusercontent.com/assets/7085132/5477004/6440429e-85f5-11e4-8728-521221cdac5a.png)
Instead of, say "lib_switch", I'd like to say "Library Switch", or instead of "floor_2_cam_ap_switch" I'd like to say "Server Room Camera/AP Switch (POE)".  At the moment, it automatically defaults to the page name.

If I've missed something (entirely possible, as I just set up the plugin yesterday), please let me know.  If you can add this feature in a future version, that would also be great.  Thanks!

**Comment by bwanders** [comment]
I'm hoping that @boozledorf's problem has been resolved. I'm closing this issue as it has been open for a while now without feedback.
